### ISSUE TITLE
Participant ID defaulting back to 1

### ISSUE THREAD

**Issue by Marsfeldt** [med-material/ArduinoReactionSynchTests#13] opened 2022-03-23 13:54 UTC
I change the participant ID in the logger to e.g. 2, but all the data is saved under ID 1.

Enter this:
![image](https://user-images.githubusercontent.com/22743681/159715221-6139b1b5-17c5-4557-b0da-a244590245c3.png)

Gets this (but with all the new data):
![image](https://user-images.githubusercontent.com/22743681/159715534-09050852-238e-4075-ab77-591a54c2ee4c.png)

Recreated on two computers.

**Comment by bastianilso** [comment] 2022-03-25 08:05
Hey Milo,
I can't reproduce your issue - changing PID from 1 to 2 works fine here and also appears on the server. And I see a few students have already used other PIDs than "1" (e.g. 40).

![image](https://user-images.githubusercontent.com/3967945/160079801-975f747c-142d-4d34-ade1-facb80f17148.png)


Did the PIDs show up correctly when you saved to CSV, Milo?

**Comment by mathiassand** [comment] 2022-03-25 08:31
I can reproduce the same error on mac. In addition, when I create a new PID (e.g. 31), it's saved in the .csv file as PID 2, which is the first PID I made.

**Comment by bastianilso** [comment] 2022-03-25 08:38
OK so the issue is that the Reconnect button is not updating the logged PID properly. so the back button is not updating it. But restarting the arduino logger works fine for updating PIDs.

**Comment by bastianilso** [comment] 2022-03-25 09:37
fixed in b4fd8ebf64a73df4cd754de0e6c7cb18074b5e66

**Closed as completed by bastianilso** 2022-03-25 09:37 UTC
